FROM ruby:2.6.6 

WORKDIR /yalaNotlob 
COPY . /yalaNotlob

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

RUN gem install rails bundler
RUN bundle install
RUN yarn install
CMD ["rails", "server", "-b", "0.0.0.0"]

